import ligop.Receiver;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ericleijonmarck' at '2016-06-23 19:13' with Gradle 2.13
 *
 * @author ericleijonmarck, @date 2016-06-23 19:13
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        System.out.println("hello");
    }
}
